app/models/electro.py
from app.extensions import db


class ELECTRO(db.Model):
    # структура данных Электро покаазаний
    __tablename__ = 'ELECTRO'

    id = db.Column(db.Integer, primary_key=True)
    month = db.Column(db.String, nullable=True)
    typeMeter = db.Column(db.String, nullable=True)
    meter = db.Column(db.String, nullable=True)

    def __init__(self, month, typeMeter, meter):
        self.month = month
        self.typeMeter = typeMeter
        self.meter = meter

    def __repr__(self):
        return '%d, %s, %s, %s' % (self.id, self.month, self.typeMeter, self.meter)

app/__init__.py
from flask import Flask

from app.extensions import db, migrate
from config import ConfigObject

from app.views.indicators import indicators
from app.views.upload import upload
from app.views.basic_view import basic_view


def create_app(config_object=ConfigObject):
    app = Flask(__name__)
    app.config.from_object(config_object)

    register_extensions(app)
    register_blueprints(app)
    app.run(host='192.168.0.102', port='5000', debug=True)
    # return app


def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app, db)


def register_blueprints(app):
    app.register_blueprint(indicators)
    app.register_blueprint(upload)
    app.register_blueprint(basic_view)

app/views/base_except_view.py
import datetime
from flask import abort
from functools import wraps
from jinja2 import TemplateNotFound


def base_view_except(f):
    # Базовый декоратор, отловщик исключений для views
    @wraps(f)
    def wraped():
        try:
            return f()
        except TemplateNotFound:
            fin = open("data/except_log.csv", 'a')
            fin.write(str(datetime.datetime.now()) + ";" + str(f.__name__) + "; TemplateNotFound\n")
            fin.close()
            abort(404, description="Resource not found")

    return wraped

app/views/basic_view.py
from flask import Blueprint, render_template, json, request
from config import indicatorsPath
from app.views.base_except_view import base_view_except


basic_view = Blueprint('basic_view', __name__, template_folder='templates')


@basic_view.route('/')
@base_view_except
def index():
    f = open(indicatorsPath, 'r')
    indicator = f.readline()
    f.close()

    hum = indicator[0:2]
    temp = indicator[3:5]
    return render_template('index.html', hum= hum, temp= temp)


@basic_view.route('/test')
@base_view_except
def test(name=None):
    return render_template('test.html', name=name)


@basic_view.route('/get_len', methods=['GET', 'POST'])
@base_view_except
def get_len():
    name = request.form['name'];
    return json.dumps({'len': len(name)})

app/views/indicators.py
import datetime
from flask import request, Response, Blueprint, render_template

from app.logic.electro_logic import admin_pg_db, import_electro, select_electro, readcsv
from app.logic.electro_logic import add_node_electro, del_nodes_electro

from app.views.base_except_view import base_view_except
from sqlalchemy.exc import SQLAlchemyError


indicators = Blueprint('indicators', __name__, template_folder='templates')


@indicators.route('/indicators')
@base_view_except
def indicators_show(name=None):
    # показывает таблицу electro из бд
    try:
        t = select_electro()
        print("m")
        return render_template('indicators.html',  t=t.all())
    except SQLAlchemyError as e:
        error = str(e.__dict__['orig'])
        print(error)
        return render_template('indicators.html',  t="")


@indicators.route('/add_electro', methods=['GET', 'POST'])
@base_view_except
def add_electro():
    # добавляет показания счетчика из формы в бд еще не рботает
    # Добавление зпписи из формы в бд
    if request.method == "POST":
        number = request.form
        print(number['date'] + " " + number['number'])
        add_node_electro(month=number['date'], meter=number['number'])

    t = select_electro()

    return render_template('indicators.html',  t=t.all())


@indicators.route('/import_csv')
@base_view_except
def import_csv(name=None):
    # импортирует данные из csv
    print(datetime.datetime.today())
    import_electro()
    t = select_electro()
    return render_template('indicators.html',  t=t.all())


@indicators.route('/export_csv')
@base_view_except
def export_csv():
    # Экспорт данных в csv на данный момент только наработка (выгружает просто таблицу не из бд)
    t = select_electro()
    j = []
    for i in t:
        j.append(str(i))
    csv = ("\n".join(j)).replace(",", ";")

    return Response(csv, mimetype="text/csv",
                    headers={"Content-disposition": "attachment; filename= myplot.csv"})


@indicators.route('/control')
@base_view_except
def drop_nodes_electro():
    # Удаляет все записи в ELECTRO
    print(24)
    del_nodes_electro()
    t = select_electro()
    return render_template('indicators.html',  t=t.all())


@indicators.route('/admin_pg')
@base_view_except
def admin_pg():
#     настроичная функция
    admin_pg_db()

app/views/upload.py
import flask
from flask import Blueprint, render_template, jsonify

from config import pathWork
from app.views.base_except_view import base_view_except


upload = Blueprint('upload', __name__, template_folder='templates')


@upload.route('/upload', methods=['GET', 'POST'])
@base_view_except
def upload_files():
    # Загрузка файлов на сервер
        if flask.request.method == "POST":
            files = flask.request.files.getlist("files")
            # Не пустой ли список файлов
            if files[0].filename == '':
                return render_template('upload.html')
            count = 0
            for file in files:
                file.save(pathWork+file.filename)
                count += 1
            print(count)
            return jsonify(htmtext='upload.html', count=count, cou= 666)
        else:
            return render_template('upload.html', count=0)

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Home</title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/reset.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/header.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">


</head>
<body>

<header>
    <nav class="menu">
        <ul>
            <li><a href="{{ url_for('basic_view.index') }}" class="linkhead">Изба</a></li>
            <li><a href="{{ url_for('upload.upload_files') }}" class="linkhead">Загрузка</a></li>
            <li><a href="{{ url_for('indicators.indicators_show') }}" class="linkhead">Показатели</a></li>
            <li><a href="{{ url_for('basic_view.test') }}" class="linkhead">Тест</a></li>
        </ul>
    </nav>
</header>


    <h1>Влажность - {{hum}}</h1>

    <h1>Температура- {{temp}}</h1>




</body>
</html>

app/templates/indicators.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/reset.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/header.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/indicators.css') }}">
</head>
<header>
    <nav class="menu">
        <ul>
            <li><a href="{{ url_for('basic_view.index') }}" class="linkhead">Изба</a></li>
            <li><a href="{{ url_for('upload.upload_files') }}" class="linkhead">Загрузка</a></li>
            <li><a href="{{ url_for('indicators.indicators_show') }}" class="linkhead">Показатели</a></li>
            <li><a href="{{ url_for('basic_view.test') }}" class="linkhead">Тест</a></li>
        </ul>
    </nav>
</header>
<body>

    <div class="left_col">
        <ul>
            <li><a href="" >add Node</a></li>
            <li><a href="{{url_for('indicators.import_csv')}}" >Import CSV</a></li>
            <li><a href="{{url_for('indicators.export_csv')}}" >Export CSV</a></li>
            <li><a href="" >Del Node</a></li>
            <li><a href="{{url_for('indicators.drop_nodes_electro')}}" >Del All</a></li>
        </ul>
    </div>

    <div class="right_col">

        <form action="/add_electro" method="POST" name="form" class="electro_form">
            <input type="date" name="date" class="input_date">
            <input type="number" name="number" class="input_metr">
            <input type="submit" value="Отправить">
        </form>

        <table>

            <tr>
                <th>ID</th>
                <th>Дата показаний</th>
                <th>Тариф</th>
                <th>Показания</th>
            </tr>
            {% if t == "" %}
            <td>
                <th>0</th>
                <th>0</th>
                <th>0</th>
                <th>0</th>
            </td>
            {% else %}
                {% for i in t%}
                <tr>
                    <td> {{i.id}}</td>
                    <td> {{i.month}}</td>
                    <td> {{i.typeMeter}}</td>
                    <td> {{i.meter}}</td>
                </tr>
                {% endfor %}
            {% endif %}
        </table>
    </div>
</body>
</html>

app/templates/test.html
<!DOCTYPE html>
<html>

 <head>
  <meta charset="utf-8">
  <title>Отправка файла на сервер</title>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/reset.css') }}">
      <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/header.css') }}">
      <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">

      <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/test.css') }}">


      <script type=text/javascript src="{{ url_for('static', filename='js/jquery-3.5.1.js') }}"></script>
      <script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>
      <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>

 </head>

<body>


    <header>
        <ul class="menu">
            <li><a href="{{ url_for('basic_view.index') }}" class="linkhead">Изба</a></li>
            <li><a href="{{ url_for('upload.upload_files') }}" class="linkhead">Загрузка</a></li>
            <li><a href="{{ url_for('indicators.indicators_show') }}" class="linkhead">Показатели</a></li>
            <li><a href="{{ url_for('basic_view.test') }}" class="linkhead">Тест</a></li>
        </ul>
    </header>


<h1>Welcome!</h1>
<button id = "factorial">Click Here!</button>

<p>Factorial: <span id='factor'>0</span></p>



<script>
        function get_len() {
            $.ajax({
                type: "POST",
                url: "/get_len",
                data: $('form').serialize(),
                type: 'POST',
                success: function(response) {
                    var json = jQuery.parseJSON(response)
                    $('#len').html(json.len)
                    console.log(response);
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }
    </script>
    <form action="/get_len" method="post" name="form">
        <label for="name">Введите текст:</label>
        <input id="name" name="name" type="text">
        <input type="button" value="Отправить" onclick="get_len();">
    </form>
    <div id="len"></div>




<h2 class="pisun">Теребонька</h2>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>

 </body>
</html>

app/templates/upload.html
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>Отправка файла на сервер</title>

      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/reset.css') }}">
      <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/header.css') }}">
      <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">

      <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/multiform.css') }}">

     <script type=text/javascript src="{{ url_for('static', filename='js/jquery-3.5.1.js') }}"></script>
     <script type="text/javascript" src="{{ url_for('static', filename='js/uploadFiles.js') }}"></script>

 </head>

 <body>

    <header>
        <ul class="menu">
            <li><a href="{{ url_for('basic_view.index') }}" class="linkhead">Изба</a></li>
            <li><a href="{{ url_for('upload.upload_files') }}" class="linkhead">Загрузка</a></li>
            <li><a href="{{ url_for('indicators.indicators_show') }}" class="linkhead">Показатели</a></li>
            <li><a href="{{ url_for('basic_view.test') }}" class="linkhead">Тест</a></li>
        </ul>
    </header>


   <h1>File input</h1>



     <form id="data" enctype="multipart/form-data" method="post" class="multform">

        <label for="fusk1" class = lab1>Open</label>
        <input  id = "fusk1"type="file" name="files" multiple="true" class="inputfile">

        <label for="fusk" class = lab2>Sent</label>
        <input id="fusk"type="submit" value="Submit" class="inputfile">

     </form>

    <h1>Progress: <span id='pBar'>0%</span></h1>

    <!--<span id='pBar2'>0</span>-->
    <h1>Успех - <span id='pBar2'>0</span></h1>





 </body>
</html>